#!/bin/bash

# Copyright (C) 2022-2023 Ole Tange, http://ole.tange.dk and Free
# Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses/>
# or write to the Free Software Foundation, Inc., 51 Franklin St,
# Fifth Floor, Boston, MA 02110-1301 USA
#
# SPDX-FileCopyrightText: 2022-2023 Ole Tange, http://ole.tange.dk and Free Software and Foundation, Inc.
# SPDX-License-Identifier: GPL-3.0-or-later

grep -hv '(dead)' ../src/* |
    # Merge lines ending in .
    perl -pe 's{(http\S+\.)\s}{$1}s' |
    # Grep out URLs
    grep -h -Po 'https?://[^ $$<>")}]+' |
    # Remove anchor
    perl -pe 's/#.*//' |
    perl -pe 's/(&gt|\{).*//;s/\\-/-/g;s/\\n//g;s/&amp;/&/g;s/&#.*//;s/\s*//;'"s/'.*//;" |
    # Remove spacing
    perl -pe 's/\s*$/\n/' |
    perl -pe 's/&quot;$//g; s/&$//g; s/\\//g;' |
    grep -Ev 'parallel-(20)?$$|coolwebsite.biz' |
    sort -u |
    egrep -v 'example.com|##|\*\(' |
    parallel -j0 --timeout 10 --bar --tag --joblog joblog --retries 3 neno wget -l1 -Q1 -U "'"'"'"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1)"'"'"'"  '{=$_=Q($_)=}'
